













name: Java CI with Maven
env: 
  IP_SERVER: ${{ secrets.ip }}
  USER: ${{ secrets.user }}
  PASSWORD: ${{ secrets.key }} # Or as an environment variable
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    name: Build Maven app
    runs-on: ubuntu-latest
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload result if build
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target
  deploy:
    name: Deploy artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name : Downloading artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
    - name : Checking files
      run: |
            cd ../
            ls 
    - name : Downloading 
      run: sudo apt-get install sshpass -y
    - name : Sshpass  
      run: |
        export SSHPASS=$PASSWORD 
        sshpass -e ssh $USER@$IP_SERVER
    - name : Scp copy  
      run: scp -r JavaSimpleProj $USER@$IP_SERVER:/var/www/backend/build
    # JavaSimpleProj - name of project
    #scp $PASSWORD -r my-artifact $USER@$IP_SERVER:/home/$USER     
    # - name : Downloading artifact to server
    #    shell: bash
    #     run: |
    #       scp -r my-artifact ${{env.USER}}@${{env.IP_SERVER}}:/var/www/backend

    
